baseURL = 'https://peterhadac.github.io/recipes/'
theme = "hugo-whisper-theme"
languageCode = 'en-us'
title = 'Recipes'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Recipes"
    url = "/recipes/"
    weight = 2

[params]
  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

    [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic Themes</a>'
